from datetime import datetime
import os

class Reporter:

    def __init__(self, ssh_data, jenkins_data, reports_dir="reports"):
        self.ssh_data = ssh_data
        self.jenkins_data = jenkins_data
        self.date = datetime.now().strftime("%Y%m%d")
        self.reports_dir = reports_dir

    def generate_md(self):
        md = f"# DevOps Daily Report ({self.date})\n\n"

        md += "## 🖥️ Server Health\n"
        for name, data in self.ssh_data.items():
            md += f"### {name}\n"
            for cmd, output in data.items():
                md += f"**{cmd}:**\n```\n{output}\n```\n"
            md += "\n"

        md += "\n## 🔧 Jenkins Status\n"
        for job, data in self.jenkins_data.items():
            md += f"- **{job}**: #{data['number']} - {data['status']}\n"

        md += "\n---\n"
        md += "_Generated by DevOps Insight Tool (EN/CN/ES Ready)_\n"
        return md

    def save(self):
        content = self.generate_md()
        filename = os.path.join(self.reports_dir, f"reports_{self.date}.md")
        with open(filename, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"Report saved: {filename}")
    
